import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:encrypt/encrypt.dart' as enc;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:isar/isar.dart';
import 'package:local_auth/local_auth.dart';
import 'package:pointycastle/export.dart' as pc;
import 'package:uuid/uuid.dart';

import '../core/constants/app_constants.dart';
import '../core/constants/strings_nl.dart';
import '../core/error/failures.dart';
import '../core/platform/platform_detector.dart';
import '../features/vault/data/models/medical_record_model.dart';
import '../features/vault/domain/entities/medical_record.dart';

// ── Provider ──────────────────────────────────────────────────────────────────

/// Global Isar instance – overridden in [main.dart] on mobile.
/// On web this provider is never resolved; [LocalVaultService] guards all
/// Isar access behind [PlatformDetector.isVaultSupported].
final isarProvider = Provider<Isar>((_) => throw UnimplementedError(
    'isarProvider must be overridden in ProviderScope on mobile.'));

final localVaultServiceProvider = Provider<LocalVaultService>((ref) {
  final isar =
      PlatformDetector.isVaultSupported ? ref.watch(isarProvider) : null;
  return LocalVaultService(isar: isar);
});

// ── Service ───────────────────────────────────────────────────────────────────

/// # LocalVaultService
///
/// Manages the Zero-Knowledge local encrypted vault on mobile.
///
/// ## Security Design
/// * **AES-256-GCM** authenticated encryption – provides both confidentiality
///   and integrity. A random 96-bit GCM nonce is generated per-record.
/// * **Key custody**: the 256-bit master key is generated by
///   [SecureRandom] (Fortuna PRNG) and persisted exclusively in the OS
///   Keychain (iOS) / Android Keystore via [flutter_secure_storage]. It is
///   NEVER written to Isar or any non-secure store.
/// * **Biometric gate**: every vault open operation requires biometric
///   verification (fingerprint / FaceID) before the key is released from
///   [flutter_secure_storage].
/// * **Self-destruct**: after [AppConstants.maxFailedAuthAttempts] consecutive
///   failures the master key AND all Isar records are permanently deleted.
/// * **Platform guard**: all operations return [VaultNotSupportedFailure]
///   on web; the web platform uses only the ephemeral RAM store exposed by
///   the WebRTC P2P viewer.
class LocalVaultService {
  LocalVaultService({required Isar? isar}) : _isar = isar;

  final Isar? _isar;
  final _secureStorage = const FlutterSecureStorage(
    // Android: encrypt using the Android Keystore at EncryptedSharedPreferences
    aOptions: AndroidOptions(encryptedSharedPreferences: true),
    // iOS: store in the Keychain accessible only when device is unlocked
    iOptions: IOSOptions(
        accessibility: KeychainAccessibility.first_unlock_this_device),
  );
  final _localAuth = LocalAuthentication();
  final _uuid = const Uuid();

  // Cached AES key for the lifetime of an unlocked session.
  enc.Key? _sessionKey;

  // ── Public API ─────────────────────────────────────────────────────────────

  /// Returns true when the vault has been initialised (key exists in storage).
  Future<bool> isVaultInitialised() async {
    if (!PlatformDetector.isVaultSupported) return false;
    final key = await _secureStorage.read(key: AppConstants.vaultKeyStorageKey);
    return key != null;
  }

  /// Creates and persists a new AES-256 vault key.
  /// Must only be called once during first-run setup.
  Future<void> createVault() async {
    _assertMobileOnly();
    final key = _generateSecureKey();
    await _secureStorage.write(
      key: AppConstants.vaultKeyStorageKey,
      value: base64Encode(key),
    );
    await _secureStorage.write(
      key: AppConstants.failedAttemptsKey,
      value: '0',
    );
  }

  /// Unlocks the vault using biometric authentication.
  ///
  /// Returns a typed [Failure] instead of throwing, so callers can pattern-
  /// match on the result without wrapping in try/catch.
  Future<({bool success, Failure? failure})> unlockWithBiometrics() async {
    _assertMobileOnly();

    final attemptsLeft = await _remainingAttempts();
    if (attemptsLeft <= 0) {
      await _selfDestruct();
      return (success: false, failure: const VaultSelfDestructFailure());
    }

    try {
      // canCheckBiometrics is true only when biometrics are enrolled;
      // isDeviceSupported also covers PIN/pattern fallback (biometricOnly: false).
      final isSupported = await _localAuth.canCheckBiometrics ||
          await _localAuth.isDeviceSupported();
      if (!isSupported) {
        return (
          success: false,
          failure: const AuthBiometricFailure(
              'Geen schermbeveiliging op dit apparaat. Stel een PIN of biometrie in via de apparaatinstellingen.'),
        );
      }

      final authenticated = await _localAuth.authenticate(
        localizedReason: StringsNl.authBiometricPrompt,
        biometricOnly: false, // allow PIN fallback
        persistAcrossBackgrounding: true,
      );

      if (authenticated) {
        await _loadSessionKey();
        await _resetFailedAttempts();
        return (success: true, failure: null);
      } else {
        return await _handleFailedAttempt();
      }
    } catch (e) {
      return (
        success: false,
        failure: AuthBiometricFailure(e.toString()),
      );
    }
  }

  /// Locks the vault by clearing the cached session key from memory.
  void lock() {
    _sessionKey = null;
  }

  /// Returns true when a session key is loaded (vault is unlocked).
  bool get isUnlocked => _sessionKey != null;

  // ── CRUD ──────────────────────────────────────────────────────────────────

  /// Encrypts and stores a [MedicalRecord] in the Isar vault.
  Future<({bool success, Failure? failure})> storeRecord(
      MedicalRecord record) async {
    _assertMobileOnly();
    if (_sessionKey == null) {
      return (success: false, failure: const VaultLockedFailure());
    }
    final isar = _isar;
    if (isar == null) {
      return (success: false, failure: const VaultNotSupportedFailure());
    }

    try {
      final encryptedPayload =
          _encryptString(record.anonymisedPayloadJson, _sessionKey!);
      final encryptedTitle = _encryptString(record.title, _sessionKey!);

      final model = MedicalRecordModel()
        ..uuid = record.id.isEmpty ? _uuid.v4() : record.id
        ..encryptedPayload = encryptedPayload
        ..encryptedTitle = encryptedTitle
        ..resourceType = record.resourceType
        ..dateRecorded = record.dateRecorded
        ..iknlGuidelineRef = record.iknlGuidelineRef
        ..fhirStatus = record.fhirStatus
        ..tagsCsv = record.tags.join(',');

      await isar.writeTxn(() async {
        await isar.medicalRecordModels.put(model);
      });
      return (success: true, failure: null);
    } catch (e) {
      return (
        success: false,
        failure: VaultEncryptionFailure('Opslaan mislukt: $e'),
      );
    }
  }

  /// Retrieves and decrypts all medical records from the vault.
  Future<({List<MedicalRecord> records, Failure? failure})>
      getAllRecords() async {
    _assertMobileOnly();
    if (_sessionKey == null) {
      return (records: <MedicalRecord>[], failure: const VaultLockedFailure());
    }
    final isar = _isar;
    if (isar == null) {
      return (
        records: <MedicalRecord>[],
        failure: const VaultNotSupportedFailure()
      );
    }

    try {
      final models =
          await isar.medicalRecordModels.where().sortByDateRecorded().findAll();

      final records = models.map((m) {
        final decryptedPayload =
            _decryptString(m.encryptedPayload, _sessionKey!);
        final decryptedTitle = _decryptString(m.encryptedTitle, _sessionKey!);
        return MedicalRecord(
          id: m.uuid,
          resourceType: m.resourceType,
          title: decryptedTitle,
          dateRecorded: m.dateRecorded,
          anonymisedPayloadJson: decryptedPayload,
          iknlGuidelineRef: m.iknlGuidelineRef,
          fhirStatus: m.fhirStatus,
          tags: m.tagsCsv.isEmpty ? [] : m.tagsCsv.split(','),
        );
      }).toList();

      return (records: records, failure: null);
    } catch (e) {
      return (
        records: <MedicalRecord>[],
        failure: VaultEncryptionFailure('Laden mislukt: $e'),
      );
    }
  }

  /// Deletes a single record by its UUID.
  Future<void> deleteRecord(String uuid) async {
    _assertMobileOnly();
    final isar = _isar;
    if (isar == null) return;
    await isar.writeTxn(() async {
      await isar.medicalRecordModels.filter().uuidEqualTo(uuid).deleteAll();
    });
  }

  /// Self-destruct: wipes ALL records AND the vault master key.
  /// Called automatically after [AppConstants.maxFailedAuthAttempts] failures
  /// or manually from the settings screen.
  Future<void> wipeVault() async {
    if (!PlatformDetector.isVaultSupported) return;
    await _selfDestruct();
  }

  // ── Encryption helpers (AES-256-GCM) ──────────────────────────────────────

  /// Encrypts [plainText] and returns a base64 string:
  ///   base64( nonce[12] || ciphertext || tag[16] )
  String _encryptString(String plainText, enc.Key key) {
    final nonce = _generateNonce();
    final iv = enc.IV(nonce);
    final encrypter = enc.Encrypter(
      enc.AES(key, mode: enc.AESMode.gcm),
    );
    final encrypted = encrypter.encrypt(plainText, iv: iv);
    // Prepend nonce so it can be reconstructed during decryption
    final combined =
        Uint8List(AppConstants.gcmNonceBytes + encrypted.bytes.length)
          ..setRange(0, AppConstants.gcmNonceBytes, nonce)
          ..setRange(
              AppConstants.gcmNonceBytes,
              AppConstants.gcmNonceBytes + encrypted.bytes.length,
              encrypted.bytes);
    return base64Encode(combined);
  }

  /// Decrypts a base64 blob produced by [_encryptString].
  String _decryptString(String encoded, enc.Key key) {
    final combined = base64Decode(encoded);
    final nonce = combined.sublist(0, AppConstants.gcmNonceBytes);
    final cipherBytes = combined.sublist(AppConstants.gcmNonceBytes);
    final iv = enc.IV(nonce);
    final encrypter = enc.Encrypter(
      enc.AES(key, mode: enc.AESMode.gcm),
    );
    return encrypter.decrypt(enc.Encrypted(cipherBytes), iv: iv);
  }

  // ── Key management ────────────────────────────────────────────────────────

  /// Loads the vault key from [flutter_secure_storage] into [_sessionKey].
  Future<void> _loadSessionKey() async {
    final encoded =
        await _secureStorage.read(key: AppConstants.vaultKeyStorageKey);
    if (encoded == null) throw const VaultKeyNotFoundFailure();
    _sessionKey = enc.Key(base64Decode(encoded));
  }

  /// Generates a cryptographically-secure 256-bit key using Fortuna PRNG.
  Uint8List _generateSecureKey() {
    final rng = pc.FortunaRandom();
    final seed = Uint8List.fromList(
        List<int>.generate(32, (_) => Random.secure().nextInt(256)));
    rng.seed(pc.KeyParameter(seed));
    return rng.nextBytes(AppConstants.aesKeyBytes);
  }

  /// Generates a cryptographically-secure 96-bit (12-byte) GCM nonce.
  Uint8List _generateNonce() {
    final rng = pc.FortunaRandom();
    final seed = Uint8List.fromList(
        List<int>.generate(32, (_) => Random.secure().nextInt(256)));
    rng.seed(pc.KeyParameter(seed));
    return rng.nextBytes(AppConstants.gcmNonceBytes);
  }

  // ── Failed-attempt tracking ────────────────────────────────────────────────

  Future<int> _remainingAttempts() async {
    final raw =
        await _secureStorage.read(key: AppConstants.failedAttemptsKey) ?? '0';
    final failed = int.tryParse(raw) ?? 0;
    return AppConstants.maxFailedAuthAttempts - failed;
  }

  Future<({bool success, Failure? failure})> _handleFailedAttempt() async {
    final raw =
        await _secureStorage.read(key: AppConstants.failedAttemptsKey) ?? '0';
    final failed = (int.tryParse(raw) ?? 0) + 1;
    await _secureStorage.write(
      key: AppConstants.failedAttemptsKey,
      value: failed.toString(),
    );

    if (failed >= AppConstants.maxFailedAuthAttempts) {
      await _selfDestruct();
      return (success: false, failure: const VaultSelfDestructFailure());
    }

    return (
      success: false,
      failure: AuthMaxAttemptsFailure(),
    );
  }

  Future<void> _resetFailedAttempts() async {
    await _secureStorage.write(
      key: AppConstants.failedAttemptsKey,
      value: '0',
    );
  }

  /// Irrevocably wipes the vault key and all stored Isar records.
  Future<void> _selfDestruct() async {
    // 1. Overwrite the key slot with zeros, then delete
    await _secureStorage.write(
      key: AppConstants.vaultKeyStorageKey,
      value: base64Encode(Uint8List(AppConstants.aesKeyBytes)), // zero-fill
    );
    await _secureStorage.delete(key: AppConstants.vaultKeyStorageKey);
    await _secureStorage.delete(key: AppConstants.failedAttemptsKey);

    // 2. Delete all Isar records (ciphertext is now orphaned without the key)
    if (_isar != null) {
      await _isar.writeTxn(() async {
        await _isar.medicalRecordModels.clear();
        await _isar.appointmentModels.clear();
      });
    }

    // 3. Clear the in-memory session key
    _sessionKey = null;
  }

  // ── Guard helper ──────────────────────────────────────────────────────────

  void _assertMobileOnly() {
    if (!PlatformDetector.isVaultSupported) {
      throw const VaultNotSupportedFailure();
    }
  }
}
